export const scaffoldTemplates = [
  { id: 'next', label: 'Next.js web' },
  { id: 'api', label: 'Express API' },
  { id: 'library', label: 'TypeScript library' },
];

export function validateProjectName(name) {
  if (typeof name !== 'string' || !/^[a-z][a-z0-9-]{0,48}[a-z0-9]$/.test(name) || name.includes('--')) {
    return 'Use 2–50 lowercase letters, numbers, or hyphens; start with a letter and end with a letter or number.';
  }
  if (/^(con|prn|aux|nul|com[1-9]|lpt[1-9])$/i.test(name)) return 'This name is reserved by Windows.';
  return '';
}

export function generateScaffold({ name, template, docker = false, ci = false }) {
  const error = validateProjectName(name);
  if (error) throw new Error(error);
  if (!scaffoldTemplates.some(item => item.id === template)) throw new Error('Choose a supported template.');
  if (docker && template === 'library') throw new Error('Docker is available for the web and API templates only.');

  const files = /** @type {Record<string, string>} */ ({});
  const json = value => JSON.stringify(value, null, 2) + '\n';
  if (template === 'next') {
    files['package.json'] = json({ name, private: true, version: '0.1.0', scripts: { dev: 'next dev', build: 'next build', start: 'next start' }, dependencies: { next: '^15.1.0', react: '^19.0.0', 'react-dom': '^19.0.0' }, devDependencies: { typescript: '^5.7.0', '@types/node': '^22.0.0', '@types/react': '^19.0.0', '@types/react-dom': '^19.0.0' } });
    files['app/layout.tsx'] = 'export default function Layout({ children }: { children: React.ReactNode }) {\n  return <html lang="en"><body>{children}</body></html>;\n}\n';
    files['app/page.tsx'] = `export default function Home() {\n  return <main><h1>${name}</h1></main>;\n}\n`;
    files['tsconfig.json'] = json({ compilerOptions: { target: 'ES2022', lib: ['dom', 'dom.iterable', 'es2022'], module: 'esnext', moduleResolution: 'bundler', jsx: 'preserve', strict: true, noEmit: true, esModuleInterop: true, skipLibCheck: true }, include: ['next-env.d.ts', '**/*.ts', '**/*.tsx'] });
  } else if (template === 'api') {
    files['package.json'] = json({ name, private: true, version: '0.1.0', type: 'module', scripts: { dev: 'tsx watch src/index.ts', build: 'tsc -p tsconfig.json', start: 'node dist/index.js' }, dependencies: { express: '^4.21.0' }, devDependencies: { typescript: '^5.7.0', tsx: '^4.19.0', '@types/express': '^4.17.0', '@types/node': '^22.0.0' } });
    files['src/index.ts'] = "import express from 'express';\nconst app = express();\napp.get('/health', (_request, response) => response.json({ status: 'ok' }));\nconst port = Number(process.env.PORT || 4000);\napp.listen(port, () => console.log(`Listening on ${port}`));\n";
    files['tsconfig.json'] = json({ compilerOptions: { target: 'ES2022', module: 'NodeNext', moduleResolution: 'NodeNext', outDir: 'dist', rootDir: 'src', strict: true, esModuleInterop: true, skipLibCheck: true }, include: ['src'] });
  } else {
    files['package.json'] = json({ name, version: '0.1.0', type: 'module', main: './dist/index.js', types: './dist/index.d.ts', files: ['dist'], scripts: { build: 'tsc -p tsconfig.json' }, devDependencies: { typescript: '^5.7.0' } });
    files['src/index.ts'] = 'export const hello = (name: string): string => `Hello, ${name}`;\n';
    files['tsconfig.json'] = json({ compilerOptions: { target: 'ES2022', module: 'NodeNext', moduleResolution: 'NodeNext', outDir: 'dist', rootDir: 'src', declaration: true, strict: true }, include: ['src'] });
  }

  const commands = template === 'library' ? 'npm install\nnpm run build' : 'npm install\nnpm run dev';
  files['README.md'] = `# ${name}\n\nGenerated by ForgeOS (${scaffoldTemplates.find(item => item.id === template).label}).\n\n\`\`\`sh\n${commands}\n\`\`\`\n`;
  files['.gitignore'] = 'node_modules/\ndist/\n.next/\n.env\n';

  if (docker) {
    const port = template === 'next' ? 3000 : 4000;
    files['Dockerfile'] = `FROM node:22-alpine\nWORKDIR /app\nCOPY package*.json ./\nRUN npm install\nCOPY . .\nRUN npm run build\nEXPOSE ${port}\nCMD ["npm", "run", "start"]\n`;
    files['.dockerignore'] = 'node_modules\n.next\ndist\n.git\n';
    files['compose.yml'] = `services:\n  app:\n    build: .\n    ports:\n      - "${port}:${port}"\n`;
  }
  if (ci) files['.github/workflows/ci.yml'] = 'name: CI\non: [push, pull_request]\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with:\n          node-version: 22\n      - run: npm install\n      - run: npm run build\n';

  for (const path of Object.keys(files)) {
    if (path.startsWith('/') || path.includes('..') || path.includes('\\')) throw new Error('Unsafe generated file path.');
  }
  return files;
}
