'use client';
import { useMemo, useState } from 'react';
import { modules, type ModuleId } from '@forgeos/contracts';

const activity = [
  ['SnapDiff', 'Baseline approved for checkout flow', '2 min ago'], ['PulseWatch', 'api.production.example recovered', '12 min ago'],
  ['ProbeAI', 'Regression suite passed: 96.4%', '32 min ago'], ['DBPulse', 'Schema migration detected in billing', '1 hr ago']
];
const statuses: Record<ModuleId, string> = { commitcraft: 'Ready', stackforge: 'Ready', snapdiff: '1 review', comparer: 'Ready', regexforge: 'Ready', loadlab: 'Ready', promptvault: '3 drafts', probeai: '1 run', pulsewatch: 'Operational', dbpulse: '2 alerts', glbviewer: 'Ready', craftcv: 'Ready', vaultiq: 'Locked' };

export default function Home() {
  const [query, setQuery] = useState(''); const [selected, setSelected] = useState<ModuleId>('snapdiff'); const [commandOpen, setCommandOpen] = useState(false);
  const filtered = useMemo(() => modules.filter(m => `${m.name} ${m.category} ${m.description}`.toLowerCase().includes(query.toLowerCase())), [query]);
  const selectedModule = modules.find(m => m.id === selected)!;
  return <main className="shell">
    <aside><div className="brand"><span>F</span> ForgeOS</div><div className="workspace">Acme Engineering <small>Cloud workspace</small></div><nav>{['Overview', 'Projects', 'Activity', 'Integrations', 'Settings'].map(x => <button key={x} className={x === 'Overview' ? 'active' : ''}>{x}</button>)}</nav><div className="nav-label">MODULES</div>{['Delivery', 'Quality', 'AI', 'Operations', 'Assets'].map(group => <section key={group}><div className="group">{group}</div>{modules.filter(m => m.category === group).map(m => <button key={m.id} onClick={() => setSelected(m.id)} className={selected === m.id ? 'selected' : ''}>{m.name}<i>{statuses[m.id]}</i></button>)}</section>)}<button className="bottom">⌘K Command palette</button></aside>
    <section className="content"><header><div><p>WORKSPACE / OVERVIEW</p><h1>Good morning, engineering.</h1><span>Everything your team is building, testing, and operating—together.</span></div><div className="actions"><button onClick={() => setCommandOpen(true)}>⌕ Search</button><button className="primary">+ New project</button><div className="avatar">GS</div></div></header>
      <div className="metrics"><Metric label="Active projects" value="12" trend="+2 this week" /><Metric label="Runs today" value="148" trend="94% successful" /><Metric label="Open incidents" value="2" trend="Needs attention" warn /><Metric label="Security score" value="92" trend="Excellent posture" /></div>
      <div className="grid"><article className="modules"><div className="title"><div><p>WORKBENCH</p><h2>Product modules</h2></div><input aria-label="Search modules" value={query} onChange={e => setQuery(e.target.value)} placeholder="Filter modules…" /></div><div className="module-grid">{filtered.map(m => <button className={`module ${selected === m.id ? 'focus' : ''}`} onClick={() => setSelected(m.id)} key={m.id}><b>{m.name.slice(0, 2).toUpperCase()}</b><span><strong>{m.name}</strong><small>{m.description}</small></span><em>{statuses[m.id]}</em></button>)}</div></article>
      <article className="selected-card"><p>{selectedModule.category.toUpperCase()} MODULE</p><h2>{selectedModule.name}</h2><span>{selectedModule.description}</span><div className="feature-list">{features[selected]!.map(f => <div key={f}>✓ {f}</div>)}</div><button className="primary">Open {selectedModule.name} →</button></article></div>
      <div className="grid bottom-grid"><article><div className="title"><div><p>LIVE</p><h2>Cross-platform activity</h2></div><button>View all</button></div>{activity.map(a => <div className="activity" key={a[0]}><b>{a[0]}</b><span>{a[1]}</span><time>{a[2]}</time></div>)}</article><article><div className="title"><div><p>OPERATIONS</p><h2>Attention needed</h2></div></div><div className="notice"><b>Critical database alert</b><span>DBPulse flagged an out-of-window schema change.</span><button>Review alert →</button></div><div className="notice"><b>2 open incidents</b><span>PulseWatch is tracking service degradation.</span><button>Open incidents →</button></div></article></div>
    </section>{commandOpen && <div className="modal" onClick={() => setCommandOpen(false)}><div onClick={e => e.stopPropagation()}><input autoFocus placeholder="Search ForgeOS modules, projects, runs…" value={query} onChange={e => setQuery(e.target.value)} />{filtered.map(m => <button key={m.id} onClick={() => { setSelected(m.id); setCommandOpen(false); }}>{m.name}<span>{m.description}</span></button>)}</div></div>}</main>;
}
function Metric({ label, value, trend, warn }: { label: string; value: string; trend: string; warn?: boolean }) { return <article className="metric"><p>{label}</p><strong>{value}</strong><span className={warn ? 'warn' : ''}>{trend}</span></article>; }
const features: Partial<Record<ModuleId, string[]>> = {
  snapdiff: ['Playwright screenshot capture', 'Pixel-level visual diffs', 'GitHub baseline approvals'], commitcraft: ['Conventional commit messages', 'PR description drafting', 'OpenAI and local model adapters'], stackforge: ['Opinionated stack templates', 'Workspace-aware scaffolds', 'Generated project tracking'], comparer: ['Images, documents, Excel, JSON, SQL, folders'], regexforge: ['Live matching', 'Multi-flavor tests', 'AI pattern explanation'], loadlab: ['K6 scripts and scenarios', 'Queued private runners', 'Performance reports'], promptvault: ['Prompt versions and branches', 'A/B experiments', 'Provider runners'], probeai: ['YAML evaluation suites', 'Multi-provider adapters', 'Regression scoring'], pulsewatch: ['Endpoint checks', 'Incident lifecycle', 'Public status pages'], dbpulse: ['Activity stream', 'Row-level changes', 'Compliance exports'], glbviewer: ['GLB/GLTF uploads', 'Share links and embeds', 'Viewer controls'], craftcv: ['Private resume editing', 'Live preview', 'PDF export'], vaultiq: ['Client-side encrypted vault', 'Password generation', 'Security scoring']
};
